"""initial schema (baseline)

Creates the pgvector extension and all tables from the SQLAlchemy models. This is a baseline
migration; subsequent schema changes should be added as autogenerated incremental migrations
(`alembic revision --autogenerate -m "..."`).

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-06
"""
from alembic import op

from app.store.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
