"""Shared contracts package — the 7 frozen interfaces (co-owned with Dev A)."""

from app.contracts.mookit import (
    Announcement,
    Assessment,
    CourseResource,
    Lecture,
    ManagedFile,
    MooKitClient,
    Question,
    TaxonomyTerm,
    User,
)
from app.contracts.types import (
    Artifact,
    ArtifactRegistry,
    ArtifactType,
    AssistantDelta,
    ErrorEvent,
    ErrorInfo,
    LLMEvent,
    LLMProvider,
    Message,
    PermissionMatrix,
    PreviewRender,
    ProposedAction,
    RequestContext,
    ResponseCompleted,
    RiskTier,
    SessionStore,
    Tool,
    ToolCallArgsDelta,
    ToolCallArgsDone,
    ToolCallStarted,
    ToolResult,
)

__all__ = [
    # types
    "Artifact",
    "ArtifactRegistry",
    "ArtifactType",
    "AssistantDelta",
    "ErrorEvent",
    "ErrorInfo",
    "LLMEvent",
    "LLMProvider",
    "Message",
    "PermissionMatrix",
    "PreviewRender",
    "ProposedAction",
    "RequestContext",
    "ResponseCompleted",
    "RiskTier",
    "SessionStore",
    "Tool",
    "ToolCallArgsDelta",
    "ToolCallArgsDone",
    "ToolCallStarted",
    "ToolResult",
    # mookit
    "Announcement",
    "Assessment",
    "CourseResource",
    "Lecture",
    "ManagedFile",
    "MooKitClient",
    "Question",
    "TaxonomyTerm",
    "User",
]
